#!/usr/bin/env python
# coding: utf-8

# In[1]:


get_ipython().system('ls')


# In[8]:


da="DUPONT ANALYSIS Operating Efficiency of the company measured in terms of profit margins has shown increasing trends. However. in the current year increase in volume and price variance was nullified by reversal of gas price incentive as disclosed in detail in note 24.1 of the financial statements. Asset Turnover remained consistent with previous years which depict that increasing revenues are being generated by effectively utilizing Company's resources. Equity Multiplier has remained consistent in previous years depicting that the increase in assets have effectively improved the equity of the company. However, increase in current period is mainly due to recovery on account of enhanced gas price which has not been recognized as revenue on prudent basis as detailed in note 24.1 of the Financial statements. POL has been posting increasing Return on Equity (ROE) for the last three years. For the year under review, ROE increase to 34.74 % as against 30.73% in the previous year. This is mainly because of an increase in crude oil prices resulting in an increase in net sales and profitability of the Company. "
spsa="Investment / Market Ratios POL core objective is to generate consistently high returns for its valued shareholders. This is reflected in steady increase in earnings of the past years and consistently dividend to its valued shareholders. POL shares are highly valued by investors and is considered as a blue chip investments due to high price earnings ratio. Share price of POL increased during the year which is testament to company ability to generate sound returns for the shareholders’ and trust of investments community’s in the company’s ability. Share Price Sensitivity The Company disseminates all material and price sensitive information to the Pakistan Stock Exchange (PSX) through Pakistan Unified Corporate Action Reporting System (PUCARS). "
prisk="Helping Our Environment We are committed to minimize and manage Environmental impacts of our operational activities on our employees, contractors, surrounding neighborhood and earth’s resources without affecting ecosystems. Keeping in view of our continual environment friendly activities, POL has been acknowledged and awarded for Environmental awards through National Forum for Environment and Health and achieved ISO 14001:2015 certification for LPG plant site Meyal. The mitigation measures taken to defy environmental impacts include technology, Management and physical controls, up gradation of systems, increased monitoring level of environmental parameters keeping in view environmental receptors, applicable legislative controls, good industrial practices and waste management etc. Trends and Uncertainties Affecting the Company's Revenue and Operations Oil prices in international market and exchange rates have significant impact on the Company's revenue which cannot be predicted reliably as it is based on variable factors not in controllable by the Company. Law and order situation especially in remote areas of KPK and interior Sindh has resulted in delayed completion of several projects and same challenge would remain in the coming year."
# print(da)
ror="""Risk 1. HSE Failure Impact • Major deviations from standards in PPL operated assets may result in \ 
multiple fatalities or serious injuries; environmental damage or pollution, production loss, and asset or \
reputational damage. Existing controls and policies • HSE management system. • Process safety \
management system. • Mechanical integrity program. • HSE internal and external audits. \
Future mitigation plan Performance during the year • Continuous implementation of \
process safety program. LTIs for PPL and contractors remained within limits. The company \
continues to be committed to highest HSE standards. • High risk contractor’s engagement through \
workshops. • Implementation of process gaps identified in road transport safety. • Management audits. \
• Compliance assessment • Automation of processes of occupational health related to incident protocols. \
investigation and risk assessment. • Behavior modification program. • Issuance of guidelines \
on Road Transport Management System Inability to replace reserves or pursue diversified growth initiatives. \
• Declining recoverable reserves. • Long term business continuity/ sustainability. • Aggressive local \
exploration program. • Aggressive pursuit of farm-in opportunities. • Re-assessment of existing producing \
assets for optimization. • Participation in bidding round. • Tight gas pilot project. • Pursue potential areas \
of diversification including power generation and mining. 3.Non-extension/ extension at unfavourable \
terms of mining leases including Sui, Kandhkot & Adhi. • Suboptimal recovery of hydrocarbons or \
pre-mature abandonment of fields. • Major outflows for extension of lease. • Accelerated production \
at Kandhkot and Adhi. This year one discovery was made in operated area. • Determination of commerciality and \
development plan for tight gas discoveries • Pursue drilling of offshore well in POP area. • Finalise D&P for Sui \
• Initiation of process for applying of lease extension for Kandhkot • Pursuit of gas price revision case in \
Kandhkot and Adhi and • Installation of Wellhead oil price revision case Compression for in Adhi. \
accelerated production at Adhi. The Sui Mining Lease expired on May 31, 2015. A MoA was executed \
between the GoP and the GoB for grant of D&PL to the Company with effect from June 01, 2015. Pending \
execution of MoA the GoP has allowed the Company to continue producing from the Sui gas field. For details \
please refer note 1.3 of the unconsolidated financial Statements for the year ended June 30, 2018. \
Lease extension strategies have been devised for both Kandhkot & Adhi assets.Risk Project \
• Delay in First execution as Gas / per defined commissioning cost, scope resulting in and timelines. \
opportunity loss.Formal internal review and risk assessment processes. Conduct of lesson learned exercises. \
Phased implementation methodology for project execution, where possible, to expedite first gas. \
• Introduction of EPCM model to provide flexibility in major projects. Default or delay in \
• Adverse settlement of cash-flows. Company’s bills by • Opportunity loss customers due to circular \
debt. • Systematic escalation and follow-up at all levels. Active follow-up for resolution of technical \
disputes. Periodic debtor’s assessment. • Engagement of public sector companies at the \
highest level for developing short term, medium term and long-term solution for circular debt and \
submission of solution to MoE. Amendment in • Financial PP 2012 exposure for resulting in reversal of \
retrospective revenues imposition of booked in WLO in Tal Accounts. Block. • No gas price incentive in Tal  \
Block under PP 2012. Existing controls and policies Future mitigation plan Performance during the \
year • Applicability of WLO in Tal Block challenged in court of law. Decline in crude oil prices. Lower  \
corporate profitability, adverse project economics. Portfolio economics analysis at 5-year plan. \
Commercial Review of all projects over Rs 500 million before execution. Availability and development  \
of required manpower. Skill gaps impacting business performance. Development of skills matrix for each \
discipline and job level.  Mentoring programs for senior staff. Asset based structure for \
greater autonomy. Staff rotation and succession planning. • Periodic Employee Engagement Survey. \
Risk Impact 9. Loss • Loss of sensitive /tampering of information, critical damage to information. \
reputation and threat of adverse legal/regulatory action. Existing controls and policies \
• Implementation of ISMS policy.  • Network based licensing. • Disaster recovery plans and data back-ups. \
• Third party security audits. Content Management Policy and E&P Data Management Policy implemented. \
Security incidents at locations disrupting operations and exploratory efforts • Potential loss of \
life or injury, delays in business activity, damage to reputation. • Implementation of Hybrid Security Model. \
Improved security infrastructure at well sites. Continuous liaison with LEAs/ Intelligence Agencies. \
• Improved security arrangement at HO.
"""

roe="""SIX YEARS’ SUMMARY  2012-13 2013-14 2014-15 2015-16 2016-17 2017-18 Return on Equity (%) 28 30 20 9 17 19."""
spsaPPL="""Share Price Low / Year End / High (Rs) mHigh Year end slow 224.50 2017-18 214.90 143.00 —— es 194 87 2016-17 148.14 Es | 37 8 () es | 68.75 2015-16 155.05 98.42 237.50 2014-15 164.26 Ss | 45 Sf Ls 261.80 2013-14 224.34 —— es | 88 (0) es 229,75 ES —_—_— es | 7() | ()"""

rumm="""Risk 1. HSE Failure Impact • Major deviations from standards in PPL operated assets may result in multiple fatalities or serious injuries; environmental damage or pollution, production loss, and asset or reputational damage. Future mitigation plan Continuous implementation of process safety program. High risk contractor’s engagement through workshops. • Implementation of process gaps identified in road transport safety. Compliance assessment of occupational health protocols. Inability to replace reserves or pursue diversified growth initiatives. • Declining recoverable reserves. • Long term business continuity/ sustainability. Aggressive pursuit of farm-in opportunities. Participation in bidding round. Determination of commerciality and development plan for tight gas discoveries • Pursue drilling of offshore well in POP area. Non-extension/ extension at unfavourable terms of mining leases including Sui, Kandhkot & Adhi. • Suboptimal recovery of hydrocarbons or pre-mature abandonment of fields. • Major outflows for extension of lease. Finalise D&P for Sui • Initiation of process for applying of lease extension for Kandhkot. Installation of Wellhead Compression for accelerated production at Adhi. Project • Delay in First execution as Gas / per defined commissioning cost, scope resulting in and timelines. opportunity loss. Future mitigation plan Improvement in contracting and project management strategy for future projects. Standardisation of contract terms for efficient in project management. Default or delay in settlement of Company’s bills by customers due to circular debt. Adverse cash-flows. Opportunity loss. Maintain rigorous follow-up from SOEs at all levels. Rigorous follow-up for recovery of dues from private sector refineries where company has greater leverage. Amendment in PP 2012 resulting in retrospective imposition of WLO In Tal Block. Impact Financial exposure for reversal of revenues booked in Accounts. NO gas price incentive in Tal Block under PP 2012. Future mitigation plan Company is pursuing this matter on JV forums. Decline in crude oil prices. Lower corporate profitability, adverse project economics. Review and optimise project cost for  marginal fields. Cost optimisation strategy to enhance field life. Availability and development of required manpower. Skill gaps impacting business performance. Develop and monitor action plan based on result of engagement survey. Loss/tampering of critical information. Impact Loss of sensitive information, damage to reputation and threat of adverse legal/regulatory action. Roll out and implementation of information classification policy. Access Rights Management in line with Data Classification. Security incidents at locations disrupting  Operations and exploratory efforts. Potential loss of life or injury, delays in business activity, damage to reputation. Risk assessment and continuous monitoring. Bridge  security gaps in identified areas. Stakeholder management."""

dirrep="""Statement of Compliance with The Public Sector Companies (Corporate Governance) Rules, 2013 The Directors are pleased to state that: Appropriate accounting policies have been used in the preparation of the financial statements and any changes in accounting  policies have been disclosed. Accounting estimates are based on reasonable and prudent judgment. Systems of internal control are sound in design and have been effectively  implemented, regularly reviewed, and monitored. The reasons for significant deviations from the preceding year’s operating results have been explained in the relevant sections of the Directors’ Report. Key operating and financial data for the last six years is given in the “Six Years’ Summary” section of the Annual Report 2019. viii. Information about outstanding taxes, duties, levies and charges, is given in the notes to the accounts. ix. Significant plans and decisions in respect of corporate restructuring, business expansion and discontinuation of operations have been outlined in the Annual Report. Future prospects, risks and uncertainties have also been disclosed in the relevant sections of the Directors’ Report. The financial statements prepared by the Company’s management present a true and fair view of its state of affairs, results of operations, cash flows and changes in equity. Proper books of accounts have been maintained by the Company. The Board has complied with the principles of corporate governance. directors, the terms of their appointment and remuneration policy, are in the best  interests of the Company and in accordance with best practices. Appointment of the Chairman and other \ 
FORGING AHEAD The Key Performance Indicators relating to the Company’s social objectives and \
outcomes have been disclosed in the relevant sections of the Directors’ Report.  \
The value of investments in employee retirement funds based on the latest audited accounts  \
as at June 30, 2018 is: Rs. Million Senior Provident Fund Junior Provident Fund \
Executive Staff Gratuity Fund Non-Executive Staff Gratuity Fund Executive Staff Pension Fund \
Non-Executive Staff Pension Fund Executive Staff Pension Fund Defined Contribution (Shariah) \
Executive Staff Pension Fund Defined Contribution (Conventional) 3,125.685 1,365.547 923.410 838.187 \
6,868.836 1,806.211 1,503.231 552.077 The number of meetings of the Board and \
Board Committees held during the year and the attendance thereat by the respective \
members have been disclosed in the “Attendance of Board and Committee Meetings” section of the Annual Report \
2019. The Board and Committee gave leave of absence to the members who were unable to attend any meeting. \
Directors only receive directors’ fees for attending meeting of the Board and Board \
Committees. The details of fees paid to each director are included in the Annual Report in the section entitled ‘Attendance of \
Board and Committee Meetings’. The pattern of shareholding in the Company as at June 30, 2019 by certain classes of \
shareholders and the statements of sale and purchase of shares during the year by \
directors, executives, their spouses and minor children, are included in the ‘Pattern \
of Shareholding’ section of the Annual Report 2019. Business Outlook Subsequent Events \
Strategy - Implementation of ISO 27001:2013 based ISMS Policy - Disaster Recovery Plans and data back-ups \
- Advanced Rights Management System (RMS) and Multi-factor Authentication (MFA) implemented Your Company continues to pursue its growth \
based strategy for exploration and development activities to contribute towards the energy \
demands of our nation. The Company is committed to actively participate in the upcoming \
exploration bid rounds to expand and diversify its exploration portfolio as part of its strategy for \
increasing hydrocarbon reserves. Change of Directors 2018-19 Performance \
Information classification policy was rolled out. The policy is being implemented in a \
phased manner. With the spud-in of Madain X-1 in Iraq in 2019, the Company has become Pakistan’s first public \
sector E&P Company to drill a well internationally. The Company is planning to \
expand its international portfolio to become a major contributor towards the energy security of \
Pakistan. Subsequent to year-end, the Board of Directors have recommended payment of final cash \
dividend of Rs 2.00 per share (20%) on ordinary shares, Rs 2.00 per share (20%) on convertible \
preference shares, 20% bonus shares to ordinary shareholders and 10% bonus shares to \
convertible preference shareholders for the year ended June 30, 2019. It is subject to \
approval by the shareholders at the forthcoming Annual General Meeting. \
9. Loss/Tampering of Critical Information Risk Statement Loss/tampering or theft of critical information \
Impact Loss of sensitive information, damage to reputation and threat of adverse \
legal/regulatory action 10. Security Risk Statement Security incidents at locations disrupting \
operations and exploration efforts Impact Potential loss of life or injury, delays in \
business activity, damage to reputation Strategy - Implementation of Hybrid Security Model \
- Continuous liaison with Law Enforcement/Intelligence agencies \
- Improved security infrastructure at well sites - Compliance/implementation of Security SOPs \
The Company plans to accelerate development of discoveries and optimize its output from existing \
/mature producing fields. Furthermore, the Company intends to evaluate diversification in \
minerals and energy sectors and is actively pursuing mining activities in lead, zinc and iron \
ore. 2018-19 Performance No major security incident has occurred  \
during the year. The mitigations in place have remained effective. Mr. Passand Khan Buledi who was appointed \
director on 26th June, 2019 resigned from directorship of the Company on 3rd September, 2019. \
Dividend/Bonus Block award Subsequent to year end, Punjab block has been provisionally awarded to PPL. \
Auditors The Company’s auditors Messrs. A.F.Ferguson & Co., who retire at the forthcoming Annual \
General Meeting are eligible for reappointment for the year 2019-20 and have been \
recommended by the Board of Directors for reappointment."""

unmm="""HSE Failure Strategy - HSE Management System - Process Safety Management System - HSE Internal and External Audits - Automated incident investigation and risk assessment 2018-19 Performance Fatality of one contractor staff occurred during drilling operations. Specific measures have been taken to avoid recurrence. Reserves Replacement Strategy - Frontier focused exploration program - Continued pursuit of farm-in opportunities - Approaching GoP with other E&P companies to expedite and announce regular bidding rounds - Determination of commerciality and development plan for tight gas discoveries - Evaluation of international E&P opportunities 2018-19 Performance - Two new blocks were acquired during the bidding round. Tight gas and offshore opportunities were also explored. - The Company made several discoveries adding reserves. - Study to rank countries/basins in line with the Company’s criteria for international E&P opportunities was completed. Lease Extension (Sui, Kandhkot, Adhi & Mazarani) Strategy - Accelerated production at Kandhkot & Adhi - Pursuit of gas price revision case in Mazarani, Kandhkot and Adhi and oil price revision case in Adhi - Continual engagement / follow-up with the Government for further extension in Sui lease / grant of D&PL 2018-19 Performance - Options to process the additional production from Kandhkot were assessed - Grant of Sui D&PL was actively followed up - Provisional extension of Mazarani lease for 3 months was obtained. Project Execution Strategy - Formal internal review and risk assessment process - Lessons learnt exercises  - Introduction of EPCM model to provide flexibility in major projects 2018-19 Performance - GPF III contract terminated. Refer section on Gambat South - EPCM model was used for Gambat South GPF-IV and Adhi compression. Phase I of GPF-IV was completed while Phase II is in progress - MDRL has been awarded for BLZ project. Feasibility Study is in advanced stage of completion - Regulatory approvals are being sought for Hatim / Faiz power plant project Windfall Levy on Oil in Tal Block Strategy  - Litigation is being contested through external lawyer 2018-19 Performance Legal proceedings underway. Outcome is dependent on the court decision. Company is reasonable confident for a favourable outcome. Decline in Crude Oil Prices Strategy - Portfolio stress test in 5-year plan for various price scenarios - Commercial review of all projects over Rs 500 million before execution 2018-19 Performance There have been no sharp declines in prices which remained in the range of USD 50 to USD 85 per barrel during the year. Crude oil prices were regularly monitored to assess the impact on short-term and long-term profitability Loss/Tampering of Critical Information Strategy - Implementation of ISO 27001:2013 based ISMS Policy - Disaster Recovery Plans and data back-ups - Advanced Rights Management System (RMS) and Multi-factor Authentication (MFA) implemented 2018-19 Performance  Information classification policy was rolled out. The policy is being implemented in a phased manner. """
print(unmm)


# In[42]:


import PyPDF2

file = open('ogdc_2018.pdf', 'rb')
# creating a pdf reader object
fileReader = PyPDF2.PdfFileReader(file)
page = fileReader.getPage(14)e.extractText().replace('\n',' ')


# In[37]:


from pdf2image import convert_from_path
# 53-64

page =45
pages = convert_from_path('ogdc_2018.pdf', first_page = page, last_page = page, grayscale=False)

pages[0].save('out.jpg', 'JPEG')
    
get_ipython().run_line_magic('pylab', 'inline')
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
img=mpimg.imread('out.jpg')
imgplot = plt.imshow(img)
plt.show()


# In[38]:


import cv2 
import pytesseract
import re

img = cv2.imread('out.jpg')

custom_config = r'--oem 3 --psm 1'
text = pytesseract.image_to_string(img, config=custom_config)
txt=text.replace('\n',' ')
txt=text
# txt=txt[4113:]
print(txt)
# txt.split('.')
# re.split('.',txt)


# In[3]:



import nltk
import os
import string
import numpy as np
import copy
import pandas as pd
import pickle
import re
import math

nltk.download("popular")
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from collections import Counter



def remove_stop_words(data):
    stop_words = stopwords.words('english')
    words = word_tokenize(str(data))
    new_text = ""
    for w in words:
        if w not in stop_words and len(w) > 1:
            new_text = new_text + " " + w
    return new_text

def convert_lower_case(data):
    return np.char.lower(data)

def remove_punctuation(data):
    symbols = "!\"#$%&()*+-./:;<=>?@[\]^_`{|}~\n"
    for i in range(len(symbols)):
        data = np.char.replace(data, symbols[i], ' ')
        data = np.char.replace(data, "  ", " ")
    data = np.char.replace(data, ',', '')
    return data

def remove_apostrophe(data):
    return np.char.replace(data, "'", "")

def num_there(s):
    for cr in s:
        if cr.isdigit():
            return True
    return False

def remNumAndSmallWords(data):
    data=data.replace(" ", "")
    if data.replace(".", "", 1).isdigit() or len(data)<3:
        return ""
    elif num_there(data):
        return ""
    else:
        return data

def remove_slashN(data):
    data=np.char.replace(data, '\n', ' ')
    return data

def preprocess(data):
    data = remove_slashN(data)
    data = convert_lower_case(data)
    data = remove_punctuation(data) #remove comma seperately
    data = remove_apostrophe(data)
    data = remove_stop_words(data)
    data = remove_punctuation(data)
    data = remove_punctuation(data) #needed again as num2word is giving few hypens and commas fourty-one
    data = remove_stop_words(data) #needed again as num2word is giving stop words 101 - one hundred and one
    data = remNumAndSmallWords(data)
    return data


# In[202]:


s="aa\na2"
print(remove_slashN(s))


# In[4]:


get_ipython().run_line_magic('pylab', 'inline')
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from pdf2image import convert_from_path
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import cv2 
import pytesseract
import re

textList=[]
tempTextList=[]
textList_years=[]
iter=0
pageIter=0
page = [[80,300,124,125,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,
        65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,85,86,303],
        [45,46,47,69,70,168,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,48,167]]
for pglist in page:
    pageIter=0
    for pg in pglist:
        print(pg)
        file='ppl_2018.pdf'
        if iter==1:
            file='ppl_2019.pdf'
        pages = convert_from_path(file, first_page = pg, last_page = pg, grayscale=False)
        pages[0].save('out.jpg', 'JPEG')

        img=mpimg.imread('out.jpg')
        imgplot = plt.imshow(img)
        plt.show()

        img = cv2.imread('out.jpg')
        custom_config = r'--oem 3 --psm 1'
        text = pytesseract.image_to_string(img, config=custom_config)
        txt=text.replace('\n',' ')
        if iter==0:    
            if pg==80:
                finalTxt=txt[1316:]
            elif pg==300:
                finalTxt+=ror
                tempTextList.append(finalTxt)
            elif pg==124:
                finalTxt=roe
                tempTextList.append(finalTxt)
            elif pg==125:
                finalTxt=spsaPPL
                tempTextList.append(finalTxt)
            elif pg==303:
                finalTxt=rumm
                tempTextList.append(finalTxt)
            elif pg==36 or pg==38:
                finalTxt=txt
            elif pg>38 and pg<=79 or pg>=85 and pg<=85:
                finalTxt+=txt
            elif pg==86 or pg==37:
                finalTxt+=txt
                tempTextList.append(finalTxt)
            else:
                finalTxt=txt
                tempTextList.append(finalTxt)
        if iter==1:
            if pg==45:
                finalTxt=txt[3280:]
            elif pg==69:
                finalTxt=txt[2237:]
            elif pg==70:
                finalTxt+=txt[4113:]
                tempTextList.append(finalTxt)
            elif pg==47:
                finalTxt+=txt[:1100]
                tempTextList.append(finalTxt)
            elif pg==168:
                finalTxt=''
                tempTextList.append(finalTxt)
            elif pg==167:
                finalTxt=unmm
                tempTextList.append(finalTxt)
            elif pg==48:
                finalTxt+=dirrep
                tempTextList.append(finalTxt)
            elif pg==31:
                finalTxt=txt
            elif pg>45 and pg<47 or pg>31 and pg<=44:
                finalTxt+=txt
            else:
                finalTxt=txt
                tempTextList.append(finalTxt)
        pageIter+=1
    iter+=1
    textList_years.append(tempTextList)
    tempTextList=[]
print(len(textList_years))
print(textList_years)


# In[5]:


textList_years[1][5]


# In[7]:


textList = [i + str(j) for i, j in zip(textList_years[0], textList_years[1])]
print(len(textList_years[0]))
print(len(textList))
print(textList)


# In[8]:


newTextList=[]
newPara=''
for para in textList:
    wordList=para.split(' ')
    newPara=''
    for word in wordList:
        newPara+=" "+str(preprocess(word))
#         print(preprocess(word))
    newTextList.append(newPara)
print(len(newTextList))


# In[201]:


print(newTextList)


# In[9]:


# print(newTextList)
vectorizer = TfidfVectorizer(ngram_range=(1,3))
vectors = vectorizer.fit_transform(newTextList)
feature_names = vectorizer.get_feature_names()
dense = vectors.todense()
denselist = dense.tolist()
df = pd.DataFrame(denselist, columns=feature_names)
df


# In[10]:


import numpy as np

nlargest = 20
topnlocs = np.argsort(-df.values, axis=1)[:, 0:nlargest]
topnlocs


# In[11]:


i=0
cols=df.columns.values.tolist()
sections=['RISK AND OPPORTUNITY REPORT','DUPONT ANALYSIS','SHARE PRICE SENSITIVITY ANALYSIS','MANAGING DIRECTOR’S REVIEW','DIRECTORS’ REPORT','PRINCIPAL RISKS/UNCERTAINTIES AND MITIGATION MEASURES']
context_list=[]
para_list=[]
for arr in topnlocs:
    para_list=[]
    for val in arr:
       para_list.append(cols[val])
    context_list.append(para_list)
    i+=1
print(context_list)


# In[27]:


# [['business', 'oil', 'reserves', 'may', 'gas', 'oil gas', 'prices', 'production', 'activities', 'carry', 'operational', 'opportunities', 'reserves may', 'operational cash', 'may impact', 'operational cash flows', 'data', 'crude', 'pak', 'boost'],
#  ['net', 'turnover', 'total assets turnover', 'total assets', 'net profit', 'assets turnover', 'yoy', 'margin', 'net profit margin', 'profit margin', 'total', 'assets', 'profit', 'year', 'assets turnover net', 'net sales', 'dupont analysis', 'turnover net', 'dupont', 'turnover net profit'],
#  ['share price', 'price', 'share', 'impact share price', 'impact share', 'business', 'impact', 'oil', 'improvement', 'security', 'stability', 'macroeconomic', 'reduces', 'positive impact share', 'positive', 'activities', 'political', 'factors', 'infrastructure', 'positive impact'],
#  ['production', 'company', 'oil', 'gas', 'billion', 'respectively', 'year', 'ogdcl', 'barrels', 'district', 'oil gas', 'moreover', 'wells', 'seismic', 'country', 'discoveries', 'fiscal year', 'total', 'fiscal', 'seismic data'],
#  ['company', 'board', 'ogdcl', 'year', 'gas', 'billion', 'production', 'governance', 'oil', 'directors', 'barrels', 'corporate governance', 'per', 'june', 'corporate', 'mmcf', 'business', 'annual', 'khan', 'financial'], 
#  ['risk', 'oil', 'ogdcl', 'company', 'production', 'gas', 'risk ogdcl', 'risks', 'reserves', 'currency', 'exploration', 'prices', 'operations', 'financial', 'business', 'operational', 'crude', 'oil gas', 'crude oil', 'fields']]
par=textList[5].replace(';','.').replace(',','.').split('.')
cwords=context_list[5]
sentList=[]
sentScore=[]
cnt=0
for pr in par:
    cnt=0
    for wrd in cwords:
        if wrd in pr.lower():
            cnt+=1
    sentScore.append(cnt)
# print(par)   
# sortedSent=sorted(sentScore, reverse=True)
# print(sortedSent)
print(len(sentScore),sentScore)
loc=[]
ilocc=0
context_sentences=[]
for itr in sentScore:
    if itr>=6:
        loc.append(ilocc)
        if par[ilocc].lower().lstrip() not in context_sentences:
            context_sentences.append(par[ilocc].lower().lstrip())
    ilocc+=1
print(loc)
# for sents in loc:
#     print(par[sents])
print(len(context_sentences))
for sentenc in context_sentences:
    print(sentenc)


# In[9]:


overall_context_words=[
[
['oil', 'reserves', 'may', 'business', 'gas', 'oil gas', 'production', 'prices',
'crude', 'activities', 'operational', 'reserves may', 'may impact', 'opportunities','data', 'crude oil',
'boost', 'pak', 'operational cash', 'operational cash flows'],
['net profit', 'total assets turnover',
'turnover', 'total assets', 'assets turnover','net', 'net profit margin', 'profit margin', 'margin',
'equity', 'total', 'assets','profit', 'yoy', 'equity multiplier', 'return equity', 'return', 'multiplier',
'year','turnover net profit'],
['share price', 'price', 'share', 'impact share', 'impact', 'impact share price',
'stability', 'macroeconomic', 'positive', 'activities', 'oil','improvement', 'political', 'positive impact',
'business', 'operational', 'price vice versa', 'price vice', 'share price vice', 'positive impact share'],
['gas', 'production', 'respectively', 'oil', 'billion', 'ogdcl', 'company', 'barrels', 'year', 'district',
'oil gas', 'mmcf', 'country', 'lpg', 'wells', 'development', 'tax', 'province', 'billion billion', 'review'],
['board', 'gas', 'ogdcl', 'company', 'production', 'year', 'billion', 'directors', 'oil', 'governance', 
'barrels', 'corporate governance', 'per', 'corporate', 'mmcf', 'business', 'development', 'gas mmcf',
'financial', 'seismic'],
['risk', 'oil', 'ogdcl', 'gas', 'production', 'company', 'risk ogdcl', 'risks',
'reserves', 'currency', 'operations', 'prices', 'business', 'exploration', 'crude', 'oil gas', 'operational',
'fields', 'crude oil', 'activities']
],
[
['risk', 'company', 'risks', 'management', 'risk management', 'exploration', 'erm', 'opportunities',
 'board', 'companys', 'mpcl', 'business', 'policy', 'strategy', 'also', 'production', 'new', 'practices',
 'magnitude', 'gas'],
['year', 'return', 'increase', 'increased', 'equity', 'return equity', 'increased due', 'margin', 'net',
 'due', 'analysis', 'profit', 'compared', 'higher', 'resulted', 'assets', 'production', 'mari', 'million',
 'debts short term'],
['share price', 'share', 'information', 'price', 'movement period', 'movement', 'sensitivity analysis investor',
 'analysis investor', 'analysis investor relations', 'along turnover market', 'might affect share',
 'might affect', 'secp timely', 'secp timely manner', 'highlights', 'relations section',
 'relations section companys', 'movement period financial', 'price along turnover', 'sensitivity analysis'],
['gas', 'mpcl', 'year', 'production', 'exploration', 'company', 'block', 'blocks', 'management', 'also', 'oil',
 'new', 'risk', 'well', 'achievements', 'change', 'another', 'industry', 'mari', 'continue'],
['well', 'company', 'gas', 'board', 'data', 'directors', 'mpcl', 'block', 'year', 'internal', 'depth',
 'audit', 'management', 'mari', 'spud', 'committee', 'planned', 'per', 'production', 'control'],
['company', 'exploration', 'risks', 'mpcl', 'production', 'gas', 'risk', 'oil', 'new', 'board', 'business',
 'blocks', 'project', 'also', 'reserves', 'opportunities', 'power', 'international', 'strategy', 'nonexecutive']
],
[
['risk', 'company', 'risks', 'mitigating', 'risk management', 'oil', 'production', 'company mitigating',
 'management', 'related', 'oil gas', 'drilling', 'business', 'gas', 'factors', 'challenges', 'exploration',
 'mitigating risk', 'company mitigating risk', 'also'],
['equity', 'increase', 'previous', 'increasing', 'assets', 'however', 'note', 'return', 'gas price',
 'consistent previous years', 'consistent previous', 'remained', 'remained consistent', 'previous years',
 'remained consistent previous', 'years', 'year', 'net', 'current', 'mainly'],
['valued', 'shareholders', 'valued shareholders', 'generate', 'returns', 'consistently',
 'company ability', 'investments', 'pol', 'price', 'ability', 'high', 'share price', 'earnings',
 'company', 'share', 'price pol', 'price earnings ratio', 'price earnings', 'increase earnings past'],
['limited', 'attock', 'limited attock', 'experience', 'pakistan', 'management', 'petroleum',
 'years work experience', 'various management', 'years work', 'posts', 'abroad', 'work experience',
 'pvt', 'pvt limited', 'director', 'refinery', 'work', 'refinery limited', 'pol'],
['million', 'per', 'pol', 'day', 'khaur', 'company', 'per day', 'year', 'well', 'water', 'share',
 'local', 'directors', 'students', 'community', 'education', 'progress', 'also', 'board', 'barrels'],
['risk', 'company', 'risks', 'mitigating', 'oil', 'company mitigating', 'risk management', 'management',
 'production', 'factors', 'also', 'gas', 'significant', 'oil gas', 'operations', 'drilling', 'related',
 'environmental', 'environment', 'challenges']
],
[
['risk', 'management', 'risk management', 'company', 'impact', 'performance', 'risk statement',
 'statement', 'process', 'adhi', 'gas', 'security', 'strategy', 'extension', 'kandhkot', 'business',
 'implementation', 'level', 'risks', 'companys'],
['increase', 'equity', 'due', 'net', 'profit', 'account', 'higher', 'holdings', 'profit margin',
 'exchange gain foreign', 'return equity', 'gain foreign currency', 'gain foreign', 'margin',
 'net profit margin', 'turnover', 'net profit', 'improved due', 'foreign currency holdings',
 'currency holdings'],
['year end', 'end', 'slow', 'year end high', 'end high mhigh', 'low year', 'year end slow', 'end slow',
 'low year end', 'price low', 'mhigh', 'end high', 'mhigh year end', 'mhigh year', 'share price low',
 'share price', 'high mhigh', 'high mhigh year', 'price low year', 'year'],
['company', 'ppl', 'production', 'exploration', 'development', 'also', 'energy', 'pakistan', 'increase',
 'activities', 'fields', 'gas', 'venture', 'joint', 'partners', 'joint venture', 'able', 'mining', 'efforts',
 'oil'],
['company', 'gas', 'well', 'completed', 'board', 'production', 'exploration', 'seismic', 'mmscfd',
 'year', 'directors', 'operator', 'exploration well', 'ppl', 'management', 'seismic data', 'development',
 'data', 'block', 'progress'],
['project', 'strategy', 'plan', 'performance', 'process', 'extension', 'management', 'adhi', 'kandhkot',
 'company', 'gas', 'opportunities', 'information', 'risk', 'lease', 'oil', 'sui', 'loss', 'assessment',
 'impact']
]
]

section_context_words=[]
for n in range(6):
    section_context_words.append([])
    
    
for lst in overall_context_words:
    section_context_words[0].append(lst[0])
    section_context_words[1].append(lst[1])
    section_context_words[2].append(lst[2])
    section_context_words[3].append(lst[3])
    section_context_words[4].append(lst[4])
    section_context_words[5].append(lst[5])
    
# print(len(section_context_words))

unique_words=[]
for n in range(6):
    unique_words.append([])
   

sectionCount=0
for sec in section_context_words:
    tempList=[]
    for lst in sec:
        for wrd in lst:
            if wrd not in tempList:
                tempList.append(wrd)
    unique_words[sectionCount]=tempList
    sectionCount+=1
# print(unique_words[0])

common_value=3
cWords=[]

for n in range(6):
    cWords.append([])

secCnt=0
wordOccCount=0
for sectn in unique_words:
    for uW in sectn:
        for wrdLst in section_context_words[secCnt]: 
            if uW in wrdLst:
                wordOccCount+=1
        if wordOccCount>=common_value:
            cWords[secCnt].append(uW)
        wordOccCount=0
    secCnt+=1
    
print(cWords)
                


# In[10]:


get_ipython().run_line_magic('pylab', 'inline')
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from pdf2image import convert_from_path
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import cv2 
import pytesseract
import re

textList=[]
tempTextList=[]
textList_years=[]
iter=0
pageIter=0
page = [[34,45,46,51,53,54,55,56,57,58,59,60,61,62,63,64,79,80],
        [38,39,51,52,56,57,59,60,61,62,63,64,65,66,67,68,69,70,71,88,89,90],
        [22,23,48,44,18,19,20,60,61,62,63,64,65,66,67,68,69,70,22,23],
        [23,24,25,55,50,18,19,20,21,67,68,69,70,71,72,73,74,75,76,77,78,79,80,78],
        [48,49,50,51,87,86,32,44,45,46,47,52,53,54,55,56,57,58,59,60,61,62,48,49,50,51],
        [48,49,50,51,99,98,32,44,45,46,47,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,12],
        [80,300,124,125,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,
        65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,85,86,303],
        [45,46,47,69,70,168,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,48,167]]
for pglist in page:
    pageIter=0
    for pg in pglist:
        print(str(pg)+"   "+str(pglist))
        if iter==0:
            file='ogdc_2018'
        elif iter==1:
            file='ogdc_2019'
        elif iter==2:
            file='mari_2018'
        elif iter==3:
            file='mari_2019'
        elif iter==4:
            file='pol_2018'
        elif iter==5:
            file='pol_2019'
        elif iter==6:
            file='ppl_2018'
        elif iter==7:
            file='ppl_2019'
        pages = convert_from_path(file+".pdf", first_page = pg, last_page = pg, grayscale=False)
        pages[0].save('out.jpg', 'JPEG')

        img=mpimg.imread('out.jpg')
        imgplot = plt.imshow(img)
        plt.show()

        img = cv2.imread('out.jpg')
        custom_config = r'--oem 3 --psm 1'
        text = pytesseract.image_to_string(img, config=custom_config)
        txt=text.replace('\n',' ')
        
        if iter==0:    
            if pg==45:
                finalTxt=txt[:825]
                tempTextList.append(finalTxt)
            elif pg==53 or pg==79:
                finalTxt=txt
            elif pg>53 and pg<64:
                finalTxt+=txt
            elif pg==64 or pg==80:
                finalTxt+=txt
                tempTextList.append(finalTxt)
            else:
                finalTxt=txt
                tempTextList.append(finalTxt)
        elif iter==1:
            if pg==51:
                finalTxt=txt[:240]
                tempTextList.append(finalTxt)
            elif pg==38 or pg==56 or pg==59 or pg==88:
                finalTxt=txt
            elif pg>59 and pg<71 or pg==89:
                finalTxt+=txt
            elif pg==39 or pg==57 or pg==71 or pg==90:
                finalTxt+=txt
                tempTextList.append(finalTxt)
            else:
                finalTxt=txt
                tempTextList.append(finalTxt)
        elif iter==2:    
            if pg==48:
                finalTxt=txt[2407:]
                tempTextList.append(finalTxt)
            elif pg==44:
                finalTxt=txt[2913:3505]
                tempTextList.append(finalTxt)
            elif pg==22 or pg==18 or pg==60:
                finalTxt=txt
            elif pg>60 and pg<70 or pg==19:
                finalTxt+=txt
            elif pg==23 or pg==20 or pg==70:
                finalTxt+=txt
                tempTextList.append(finalTxt)
            else:
                finalTxt=txt
                tempTextList.append(finalTxt)
        elif iter==3:
            if pg==55:
                finalTxt=txt[1630:]
                tempTextList.append(finalTxt)
            elif pg==50:
                finalTxt=txt[6277:6867]
                tempTextList.append(finalTxt)
            elif pg==23 or pg==18 or pg==67:
                finalTxt=txt
            elif pg>18 and pg<21 or pg>67 and pg<80 or pg==24:
                if pg==78 and len(pglist)-1==pageIter:
                    finalTxt=txt
                    tempTextList.append(finalTxt)
                else:
                    finalTxt+=txt
            elif pg==25 or pg==21 or pg==80:
                finalTxt+=txt
                tempTextList.append(finalTxt)
            else:
                finalTxt=txt
                tempTextList.append(finalTxt)
        elif iter==4:    
            if pg==86:
                finalTxt=txt[1174:1700]
                tempTextList.append(finalTxt)
            elif pg==48 or pg==44:
                finalTxt=txt
            elif pg>48 and pg<51 or pg>44 and pg<=47 or pg>=52 and pg<62:
                finalTxt+=txt
            elif pg==51 or pg==62:
                finalTxt+=txt
                tempTextList.append(finalTxt)
            else:
                finalTxt=txt
                tempTextList.append(finalTxt)
        elif iter==5:
            if pg==99:
                finalTxt=da
                tempTextList.append(finalTxt)
            elif pg==98:
                finalTxt=spsa
                tempTextList.append(finalTxt)
            elif pg==12:
                finalTxt=prisk
                tempTextList.append(finalTxt)
            elif pg==48 or pg==44:
                finalTxt=txt
            elif pg>48 and pg<51 or pg>44 and pg<=47 or pg>=52 and pg<69:
                finalTxt+=txt
            elif pg==51 or pg==47 or pg==69:
                finalTxt+=txt
                tempTextList.append(finalTxt)
            else:
                finalTxt=txt
                tempTextList.append(finalTxt)
        elif iter==6:    
            if pg==80:
                finalTxt=txt[1316:]
            elif pg==300:
                finalTxt+=ror
                tempTextList.append(finalTxt)
            elif pg==124:
                finalTxt=roe
                tempTextList.append(finalTxt)
            elif pg==125:
                finalTxt=spsaPPL
                tempTextList.append(finalTxt)
            elif pg==303:
                finalTxt=rumm
                tempTextList.append(finalTxt)
            elif pg==36 or pg==38:
                finalTxt=txt
            elif pg>38 and pg<=79 or pg>=85 and pg<=85:
                finalTxt+=txt
            elif pg==86 or pg==37:
                finalTxt+=txt
                tempTextList.append(finalTxt)
            else:
                finalTxt=txt
                tempTextList.append(finalTxt)
        elif iter==7:
            if pg==45:
                finalTxt=txt[3280:]
            elif pg==69:
                finalTxt=txt[2237:]
            elif pg==70:
                finalTxt+=txt[4113:]
                tempTextList.append(finalTxt)
            elif pg==47:
                finalTxt+=txt[:1100]
                tempTextList.append(finalTxt)
            elif pg==168:
                finalTxt=''
                tempTextList.append(finalTxt)
            elif pg==167:
                finalTxt=unmm
                tempTextList.append(finalTxt)
            elif pg==48:
                finalTxt+=dirrep
                tempTextList.append(finalTxt)
            elif pg==31:
                finalTxt=txt
            elif pg>45 and pg<47 or pg>31 and pg<=44:
                finalTxt+=txt
            else:
                finalTxt=txt
                tempTextList.append(finalTxt)
        pageIter+=1
    iter+=1
    textList_years.append(tempTextList)
    tempTextList=[]
print(len(textList_years))    


# In[39]:


textList = [i +"."+ str(j) for i, j in zip(textList_years[0], textList_years[1])]
textList1 = [i +"."+ str(j) for i, j in zip(textList_years[2], textList_years[3])]
textList2 = [i +"."+ str(j) for i, j in zip(textList_years[4], textList_years[5])]
textList3 = [i +"."+ str(j) for i, j in zip(textList_years[6], textList_years[7])]
# print(len(textList_years[0]))
print(len(textList))
print(len(textList1))
print(len(textList2))
print(len(textList3))
print(textList[1])


# In[19]:


section_context_sent=[]
allText=[]
allText.append(textList)
allText.append(textList1)
allText.append(textList2)
allText.append(textList3)
               
for n in range(6):
    section_context_sent.append([])

for compText in allText:
    section_context_sent[0].append(compText[0])
    section_context_sent[1].append(compText[1])
    section_context_sent[2].append(compText[2])
    section_context_sent[3].append(compText[3])
    section_context_sent[4].append(compText[4])
    section_context_sent[5].append(compText[5])
    
print(len(section_context_sent))
print(len(section_context_sent[0]))


# In[20]:


common_sentences=[]
new_secConSent=[]

for n in range(6):
    common_sentences.append([])
    new_secConSent.append([])
    
iterCount=0
for sentLists in section_context_sent:
    for sent in sentLists:
        sentences=sent.replace(';','.').replace(',','.').split('.')
        new_secConSent[iterCount].append(sentences)
    iterCount+=1

    
unique_sentences=[]
for n in range(6):
    unique_sentences.append([])
   

sectionCount=0
for sec in new_secConSent:
    tempList=[]
    for lst in sec:
        for sentense in lst:
            if sentense not in tempList:
                tempList.append(sentense)
    unique_sentences[sectionCount]=tempList
    sectionCount+=1
            
                


# In[21]:


com_context_words=[['business', 'gas', 'production', 'risk', 'company', 'risks', 'management', 'risk management'],
 ['net', 'margin', 'equity', 'assets', 'profit', 'return equity', 'return', 'year', 'increase'],
 ['share price', 'price', 'share'],
 ['gas', 'production', 'oil', 'company'],
 ['board', 'gas', 'company', 'production', 'year', 'directors', 'per', 'well'],
 ['risk', 'oil', 'gas', 'production', 'company', 'risks']]
contUniqSentences=[]
for n in range(6):
    par=unique_sentences[n]
    cwords=com_context_words[n]
    sentList=[]
    sentScore=[]
    cnt=0
    for pr in par:
        cnt=0
        for wrd in cwords:
            if wrd in pr.lower():
                cnt+=1
        sentScore.append(cnt)

#     print(len(sentScore),sentScore)
    loc=[]
    ilocc=0
    score=4
    if n==2:
        score=3
    context_sentences=[]
    for itr in sentScore:
        if itr>=score:
            loc.append(ilocc)
            if par[ilocc].lower().lstrip() not in context_sentences:
                context_sentences.append(par[ilocc].lower().lstrip())
        ilocc+=1
    contUniqSentences.append(context_sentences)


print(len(contUniqSentences))
for sentenc in contUniqSentences:
    print(len(sentenc))
print(contUniqSentences[1])


# In[29]:




from gensim import corpora, models, similarities
import jieba

def isQualified(sentence,sentList,simScore):
    maxVal=0
    texts = sentList
    keyword = sentence
    texts = [jieba.lcut(text) for text in texts]
    dictionary = corpora.Dictionary(texts)
    feature_cnt = len(dictionary.token2id)
    corpus = [dictionary.doc2bow(text) for text in texts]
    tfidf = models.TfidfModel(corpus) 
    kw_vector = dictionary.doc2bow(jieba.lcut(keyword))
    index = similarities.SparseMatrixSimilarity(tfidf[corpus], num_features = feature_cnt)
    sim = index[tfidf[kw_vector]]
    for i in range(len(sim)):
        if sim[i]>maxVal:
            maxVal=sim[i]
    if maxVal>=simScore:
        return True
    else:
        return False

common_value=3
cSentences=[]

for n in range(6):
    cSentences.append([])

secCnt=0
senOccCount=0
for sectn in contUniqSentences:
    print(secCnt)
    xCnt=0
    if secCnt==3:
        simScore=0.1
    elif secCnt==1 or secCnt==4:
        simScore=0.35
    elif secCnt==0:
        simScore=0.32
    else:
        simScore=0.37
    for uW in sectn:
        print(">>>>>>  "+str(xCnt))
        for senLst in new_secConSent[secCnt]: 
            if isQualified(uW,senLst,simScore):
                senOccCount+=1
        if senOccCount>=common_value:
            cSentences[secCnt].append(uW)
        senOccCount=0
        xCnt+=1
    secCnt+=1
    
print(cSentences)


# In[32]:


# from nltk.corpus import stopwords 
# from nltk.tokenize import word_tokenize 
  
# # X = input("Enter first string: ").lower() 
# # Y = input("Enter second string: ").lower() 
# X ="I love horror movies"
# Y ="I love horror movies"
  
# # tokenization 
# X_list = word_tokenize(X)  
# Y_list = word_tokenize(Y) 
  
# # sw contains the list of stopwords 
# sw = stopwords.words('english')  
# l1 =[];l2 =[] 
  
# # remove stop words from string 
# X_set = {w for w in X_list if not w in sw}  
# Y_set = {w for w in Y_list if not w in sw} 
  
# # form a set containing keywords of both strings  
# rvector = X_set.union(Y_set)  
# for w in rvector: 
#     if w in X_set: l1.append(1) # create a vector 
#     else: l1.append(0) 
#     if w in Y_set: l2.append(1) 
#     else: l2.append(0) 
# c = 0
  
# # cosine formula  
# for i in range(len(rvector)): 
#         c+= l1[i]*l2[i] 
# cosine = c / float((sum(l1)*sum(l2))**0.5) 
# print("similarity: ", cosine)



print(len(cSentences[0]))
print(len(cSentences[1]))
print(len(cSentences[2]))
print(len(cSentences[3]))
print(len(cSentences[4]))
print(len(cSentences[5]))

for s in cSentences[4]:
    print(s)


# In[17]:


import dill
dill.dump_session('notebook_env.db')

